name: Noetic

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04

    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          path: .ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Build
        run: .ci/build_package.sh /tmp/debs_to_push

      - name: Deploy to unstable
        run: .ci_scripts/push_to_ppa.sh /tmp/debs_to_push unstable

      - name: Deploy to stable
        run: .ci_scripts/push_to_ppa.sh /tmp/debs_to_push stable
